---
- name: Set the correct opcache filename (Ubuntu/Debian).
  set_fact:
    php_opcache_conf_filename: "10-opcache.ini"

- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present

- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Delete apt key from /etc/apt/trusted.gpg.
  ansible.builtin.apt_key:
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    keyring: /etc/apt/trusted.gpg
    state: absent

- name: Delete unsigned PHP versions repository.
  ansible.builtin.lineinfile:
    path: "/etc/apt/sources.list.d/ppa_ondrej_php_{{ ansible_distribution_release }}.list"
    regexp: '^deb http.*$'
    state: absent
    owner: root
    group: root
    mode: 0644

- name: Ensure keyring directory exists.
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add Ondrej Sury's PHP apt key.
  ansible.builtin.get_url:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
    dest: /etc/apt/keyrings/ppa_ondrej_php.asc
    owner: root
    group: root
    mode: 0644
  register: download_output
  retries: 5
  until: download_output is not failed

- name: Add Ondrej Sury's PHP repository.
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/ppa_ondrej_php.asc] https://ppa.launchpadcontent.net/ondrej/php/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main"
    filename: "ppa_ondrej_php_{{ ansible_distribution_release }}"

- name: Purge PHP version packages (besides the currently chosen php_version).
  apt:
    name: "{{ php_versions_debian | reject('search', 'php' ~ php_version) | list }}"
    state: absent
    purge: true
    force: true
  register: php_version_purge

- name: Also purge php-common package if any versions were just purged.
  apt:
    name: php-common
    state: absent
    purge: true
    force: true
  when: php_version_purge.changed | bool
